<?php

$array = [
    'lang' => 'ar',
    'AED' => 'نيات',
    'Off' => 'نيات',
    'add_to_cart' => 'إلكترونيا',
    'buy_now' => ' إلكترونيات',
    'free_shipping' => 'الشحن مجانا',
    'free_return' => 'عائد مجاني',
    'free_return_policy' => 'عودة 7 ايام عودة السياسة',
    'on_all_orders' => 'على جميع الطلبات فوق 100 درهم',
    'fragrances' => 'عطور',
    'special_offers' => 'عروض خاصة',
    'brands' => 'العلامات التجارية',
    'exclusive_brands' => 'العلامات التجارية الحصرية',
    'arabic_perfumes' => 'عطور عربية',
    'new_arrivals' => 'القادمون الجدد',
    'one_day_sale' => 'تنزيلات اليوم الواحد',
    'gift_set' => 'مجموعة هدية',
    'others' => 'الآخرين',
    'register' => 'تسجيل',
    'login' => 'تسجيل الدخول',
    'product_name' => 'اسم المنتج',
    'search_products'=>'البحث عن المنتجات',
];
